trigger: none
pr: none

resources:
  pipelines:
    - pipeline: test
      project: ALM-team-private
      source: pipeline1
      trigger: true

steps:
  - script: echo "hello, world 2"
  - script: echo "hello, world 3"
